#!/bin/bash

# Script to fetch environment variables from Secrets Manager for local development
# Usage: ./scripts/setup-local-env.sh

SECRET_NAME="byteverse-ui/env-vars"
REGION="us-east-1"
ENV_FILE=".env"

echo "Fetching configuration from Secrets Manager..."
echo "Secret: $SECRET_NAME"
echo "Region: $REGION"
echo ""

# Check if AWS CLI is available
if ! command -v aws &> /dev/null; then
  echo "Error: AWS CLI is not installed or not in PATH"
  exit 1
fi

# Check if jq is available
if ! command -v jq &> /dev/null; then
  echo "Warning: jq is not installed. JSON parsing may fail."
  echo "Install jq: brew install jq (macOS) or apt-get install jq (Linux)"
fi

# Fetch secret from Secrets Manager
SECRET_JSON=$(aws secretsmanager get-secret-value \
  --secret-id "$SECRET_NAME" \
  --region "$REGION" \
  --query SecretString \
  --output text 2>/dev/null)

if [ $? -ne 0 ]; then
  echo "Error: Failed to fetch secret from Secrets Manager"
  echo "Make sure:"
  echo "1. AWS CLI is configured (run 'aws configure')"
  echo "2. You have permissions to read the secret"
  echo "3. The AppsyncStack has been deployed"
  exit 1
fi

# Extract values and create .env file
echo "Creating .env file..."

# Required value
IDENTITY_POOL_ID=$(echo "$SECRET_JSON" | jq -r '.VITE_COGNITO_IDENTITY_POOL_ID // empty')
if [ -z "$IDENTITY_POOL_ID" ] || [ "$IDENTITY_POOL_ID" = "null" ]; then
  echo "Warning: VITE_COGNITO_IDENTITY_POOL_ID not found in secret"
  IDENTITY_POOL_ID=""
fi

# Optional values (with defaults)
AWS_REGION=$(echo "$SECRET_JSON" | jq -r '.VITE_AWS_REGION // "us-east-1"')
APPSYNC_ENDPOINT=$(echo "$SECRET_JSON" | jq -r '.VITE_APPSYNC_ENDPOINT // "https://api.byteverseinnov.com/graphql"')

# Create .env file
cat > "$ENV_FILE" <<EOF
# Local development - values fetched from Secrets Manager
# Generated by: ./scripts/setup-local-env.sh
# Secret: $SECRET_NAME

# Required for local development
VITE_COGNITO_IDENTITY_POOL_ID=$IDENTITY_POOL_ID

# Optional - defaults are used if not set
VITE_AWS_REGION=$AWS_REGION
VITE_APPSYNC_ENDPOINT=$APPSYNC_ENDPOINT
EOF

echo ""
echo "✓ .env file created successfully!"
echo ""
echo "Values set:"
echo "  VITE_COGNITO_IDENTITY_POOL_ID: ${IDENTITY_POOL_ID:0:20}... (length: ${#IDENTITY_POOL_ID})"
echo "  VITE_AWS_REGION: $AWS_REGION"
echo "  VITE_APPSYNC_ENDPOINT: $APPSYNC_ENDPOINT"
echo ""
echo "You can now run 'npm run dev' to start local development"
